version: '3.3'
services:
  rpi-jupyter-conda:
    container_name: jupyter-notebook
    image: andresvidal/jupyter-armv7l
    #image: jupyter/datascience-notebook
    # ports:
    #   - '8888:8888'
    volumes:
      - './notebooks:/root/notebooks'
      - './config/jupyter_notebook_config.py:/root/.jupyter/jupyter_notebook_config.py'
    restart: unless-stopped

networks:
  default:
    external:
      name: nginx-proxy-manager
