version: '2.1'
services:
  grocy:
    image: ghcr.io/linuxserver/grocy
    container_name: grocy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Berlin
    volumes:
      - grocy-data:/config
    # ports:
    #   - 9283:80
    restart: unless-stopped

volumes:
  grocy-data:

networks:
  default:
    external:
      name: nginx-proxy-manager
