version: '3'
services:
  codimd_mariadb:
    image: linuxserver/mariadb:latest
    container_name: codimd_mariadb
    restart: always
    volumes:
      - codimd_mariadb-data:/config
    environment:
      - MYSQL_ROOT_PASSWORD=VerrySecret
      - MYSQL_DATABASE=codimd
      - MYSQL_USER=codimd
      - MYSQL_PASSWORD=VerrySecret
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Berlin
  codimd:
    image: linuxserver/codimd:latest
    container_name: codimd
    restart: always
    depends_on:
      - codimd_mariadb
    volumes:
      - codimd-data:/config
    environment:
      - DB_HOST=codimd_mariadb
      - DB_USER=codimd
      - DB_PASS=VerrySecret
      - DB_NAME=codimd
      - DB_PORT=3306
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Berlin
    # ports:
    #   - "3000:3000"

volumes:
  codimd_mariadb-data:
  codimd-data:

networks:
  default:
    external:
      name: nginx-proxy-manager
