version: '3'

services:
  code-server:
    image: linuxserver/code-server
    container_name: code-server
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Berlin
      - PASSWORD=Morpheus.vse.2
      - SUDO_PASSWORD=Morpheus.vse.2
    volumes:
      - ./config:/config
      - ./..:/config/root
    # ports:
    #   - 8443:8443
    restart: unless-stopped

networks:
  default:
    external:
      name: nginx-proxy-manager
