---
version: '2.1'
services:
  nextcloud:
    image: ghcr.io/linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - nextcloud-config:/config
      - nextcloud-data:/data
    # ports:
    #   - 443:443
    restart: unless-stopped

volumes:
  nextcloud-data:
  nextcloud-config:

networks:
  default:
    external:
      name: nginx-proxy-manager
