version: '3'
services:
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./config/config.json:/app/config/production.json
      - ./data:/data
      - ./proxy_host:/data/nginx/proxy_host
      - ./letsencrypt:/etc/letsencrypt
    restart: unless-stopped

  nginx-prody-manager-db:
    container_name: nginx-proxy-manager-database
    image: 'yobasystems/alpine-mariadb:latest'
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: unless-stopped

networks:
  default:
    external:
      name: nginx-proxy-manager
