version: '2.1'
services:
  dokuwiki:
    image: ghcr.io/linuxserver/dokuwiki
    container_name: dokuwiki
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    # ports:
    #   - 80:80
    #   - 443:443 #optional
    volumes:
      - dokuwiki-data:/config
    restart: unless-stopped

volumes:
  dokuwiki-data:

networks:
  default:
    external:
      name: nginx-proxy-manager
