version: '2.1'
services:
  doublecommander:
    image: ghcr.io/linuxserver/doublecommander
    container_name: doublecommander
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - doublecommander-config:/config
      - doublecommander-data:/data
    # ports:
    #   - 3000:3000
    restart: unless-stopped

volumes:
  doublecommander-data:
  doublecommander-config:

networks:
  default:
    external:
      name: nginx-proxy-manager
