version: '2.1'
services:
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Berlin
    volumes:
      - ./config:/config
    # ports:
    #   - 1080:80
    #   - 1443:443
    restart: unless-stopped

networks:
  default:
    external:
      name: nginx-proxy-manager
