version: '2.1'
services:
  dillinger:
    image: ghcr.io/linuxserver/dillinger
    container_name: dillinger
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    # ports:
    #   - 8080:8080
    volumes:
      - dillinger-data:/config
    restart: unless-stopped

volumes:
  dillinger-data:

networks:
  default:
    external:
      name: nginx-proxy-manager
